/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacionGUI;

import controladores.Fabrica;
import controladores.iSistema;
import datatypes.DataSub;
import java.util.List;
import javax.swing.JOptionPane;
import persistencia.ControladorPersistencia;

/**
 *
 * @author frank
 */
public class ActualizarEstadoSubscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarEstadoSubscripcion
     */
    ControladorPersistencia cpu;
    
    iSistema sys = new Fabrica().getSistema(cpu);
    public ActualizarEstadoSubscripcion() {
        initComponents();
        cmbNick.removeAllItems();
        List<String> dts= sys.listarUsuarioSubsPendientes();
        String[] nicksA = new String[dts.size()+1];
        nicksA[0] = "Clientes";
        if(0<dts.size()){
            int i = 1;
                for(String s:dts){
                    nicksA[i]=s;
                    i++;
                }
        }
        cmbNick.setModel(new javax.swing.DefaultComboBoxModel<>(nicksA));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbNick = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha Inicio:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente:");

        cmbNick.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        cmbNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNickActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo:");

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbNick, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(txtInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(22, 22, 22)))
                .addComponent(btnSalir)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnValidar)
                    .addComponent(btnCancelar))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        sys.cambioEstadoSubscripcion((String)cmbNick.getSelectedItem(), "Cancelada");
        JOptionPane.showMessageDialog(this, "Subscripcion Cancelada.");
        cmbNick.removeAllItems();
        List<String> dts= sys.listarUsuarioSubsPendientes();
        String[] nicksA = new String[dts.size()+1];
        nicksA[0] = "Clientes";
        if(0<dts.size()){
            int i = 1;
                for(String s:dts){
                    nicksA[i]=s;
                    i++;
                }
        }
        cmbNick.setModel(new javax.swing.DefaultComboBoxModel<>(nicksA));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNickActionPerformed
        DataSub sub = sys.darSubUsuario((String)cmbNick.getSelectedItem());
        txtInicio.setText(sub.getInicio().toString());
        txtTipo.setText(sub.getTipo());
    }//GEN-LAST:event_cmbNickActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        sys.cambioEstadoSubscripcion((String)cmbNick.getSelectedItem(),"Vigente");
        JOptionPane.showMessageDialog(this, "Subscripcion Validada.");
        cmbNick.removeAllItems();
        List<String> dts= sys.listarUsuarioSubsPendientes();
        String[] nicksA = new String[dts.size()+1];
        nicksA[0] = "Clientes";
        if(0<dts.size()){
            int i = 1;
                for(String s:dts){
                    nicksA[i]=s;
                    i++;
                }
        }
        cmbNick.setModel(new javax.swing.DefaultComboBoxModel<>(nicksA));
    }//GEN-LAST:event_btnValidarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnValidar;
    private javax.swing.JComboBox<String> cmbNick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
