/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacionGUI;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import controladores.Fabrica;
import controladores.Sistema;
import controladores.iSistema;
import excepciones.UsuarioRepetidoException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
//import javax.persistence.criteria.Path;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import persistencia.ControladorPersistencia;
import persistencia.iControladorPersistencia;

/**
 *
 * @author dokgo
 */
public class AltaPerfil extends javax.swing.JInternalFrame {

    public String nickname;
    public String nombre;
    public String apellido;
    public String correo;
    public LocalDate fechaNac;
    public String imagenPerfil;
    public String sitioWeb;
    public String tipo;
    public String biografia;
    public String password;
    public String pass_conf;
    
    ControladorPersistencia cpu;
    
    iSistema sys = new Fabrica().getSistema(cpu);
    
    /**
     * Creates new form AltaPerfil
     */
    public AltaPerfil() {
        initComponents();
        this.setSize(700,700);
        
        jLabel_biografia.setVisible(false);
        jLabel_sitioWeb.setVisible(false);
        txt_biografia.setVisible(false);
        txt_sitioWeb.setVisible(false);
        
        jButton_registrarUsuario.setVisible(true);
        jButton_cancelar.setVisible(true);
        
        //sys = new Fabrica().getSistema();
        
        
        
        buttonGroup1.add(jRadioButton_Cliente);
        buttonGroup1.add(jRadioButton_Artista);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel_nickname = new javax.swing.JLabel();
        txt_nickname = new javax.swing.JTextField();
        txt_fechaNac = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel_apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel_correo = new javax.swing.JLabel();
        jLabel_fechaNac = new javax.swing.JLabel();
        jRadioButton_Cliente = new javax.swing.JRadioButton();
        jRadioButton_Artista = new javax.swing.JRadioButton();
        txt_sitioWeb = new javax.swing.JTextField();
        jButton_imagen = new javax.swing.JButton();
        jLabel_imagen = new javax.swing.JLabel();
        jLabel_tipoUsuario = new javax.swing.JLabel();
        jLabel_biografia = new javax.swing.JLabel();
        jLabel_sitioWeb = new javax.swing.JLabel();
        jButton_cancelar = new javax.swing.JButton();
        jButton_registrarUsuario = new javax.swing.JButton();
        txt_correo = new javax.swing.JTextField();
        txt_biografia = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        txt_password_confirmation = new javax.swing.JTextField();
        jLabel_password_confirmation = new javax.swing.JLabel();

        setTitle("Alta de Perfil");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nickname.setText("Nickname: ");
        getContentPane().add(jLabel_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txt_nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicknameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 260, -1));

        txt_fechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaNacActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 140, -1));

        jLabel_nombre.setText("Nombre:");
        getContentPane().add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 260, -1));

        jLabel_apellido.setText("Apellido:");
        getContentPane().add(jLabel_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 260, -1));

        jLabel_correo.setText("Email:");
        getContentPane().add(jLabel_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel_fechaNac.setText("Fecha de Nacimiento (año-mes-dia):");
        getContentPane().add(jLabel_fechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jRadioButton_Cliente.setText("Cliente");
        jRadioButton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jRadioButton_Artista.setText("Artista");
        jRadioButton_Artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ArtistaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton_Artista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, 20));

        txt_sitioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sitioWebActionPerformed(evt);
            }
        });
        getContentPane().add(txt_sitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 260, -1));

        jButton_imagen.setText("Seleccionar Imagen");
        jButton_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imagenActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        getContentPane().add(jLabel_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 230, 110));

        jLabel_tipoUsuario.setText("Tipo de Usuario:");
        getContentPane().add(jLabel_tipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel_biografia.setText("Biografia:");
        getContentPane().add(jLabel_biografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jLabel_sitioWeb.setText("Sitio Web:");
        getContentPane().add(jLabel_sitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 170, -1));

        jButton_registrarUsuario.setText("Registrar Usuario");
        jButton_registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_registrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 170, -1));

        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 260, -1));

        txt_biografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_biografiaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_biografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 260, -1));

        jLabel_password.setText("Password:");
        getContentPane().add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 260, -1));

        txt_password_confirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password_confirmationActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password_confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 260, -1));

        jLabel_password_confirmation.setText("Confirmar password:");
        getContentPane().add(jLabel_password_confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicknameActionPerformed
        nickname = txt_nickname.getText();
    }//GEN-LAST:event_txt_nicknameActionPerformed

    private void jRadioButton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ClienteActionPerformed
        if(jRadioButton_Cliente.isSelected() == true){
            jLabel_biografia.setVisible(false);
            jLabel_sitioWeb.setVisible(false);
            txt_biografia.setVisible(false);
            txt_sitioWeb.setVisible(false);  
        }
    }//GEN-LAST:event_jRadioButton_ClienteActionPerformed

    private void jRadioButton_ArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ArtistaActionPerformed
        if(jRadioButton_Artista.isSelected() == true){
            jLabel_biografia.setVisible(true);
            jLabel_sitioWeb.setVisible(true);
            txt_biografia.setVisible(true);
            txt_sitioWeb.setVisible(true);  
        }
    }//GEN-LAST:event_jRadioButton_ArtistaActionPerformed

    private void jButton_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imagenActionPerformed

        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG & PNG", "jpg", "png");
        jFileChooser.setFileFilter(filtrado);

        int respuesta = jFileChooser.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            File imagenSeleccionada = jFileChooser.getSelectedFile();
            imagenPerfil = imagenSeleccionada.getName();

            try {
                Path destino = Paths.get("src/main/resources/images/" + imagenPerfil);

                if (!Files.exists(destino)) {
                    Files.copy(imagenSeleccionada.toPath(), destino);
                }

                // mostrar la imagen en el JLabel
                Image mImagen = new ImageIcon(destino.toString()).getImage();
                ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(jLabel_imagen.getWidth(), jLabel_imagen.getHeight(), Image.SCALE_SMOOTH));
                jLabel_imagen.setIcon(mIcono);
                jLabel_imagen.setVisible(true);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, 
                    "Error: ERROR: No se pudo copiar la imagen.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_imagenActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        apellido = txt_apellido.getText();
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        this.setVisible(false);

        txt_nickname.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_correo.setText("");
        txt_fechaNac.setText("");
        txt_biografia.setText("");
        txt_sitioWeb.setText("");

        jRadioButton_Cliente.setSelected(false);
        jRadioButton_Artista.setSelected(false);

        jLabel_biografia.setVisible(false);
        jLabel_sitioWeb.setVisible(false);
        txt_biografia.setVisible(false);
        txt_sitioWeb.setVisible(false);

    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        nombre = txt_nombre.getText();
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        correo = txt_correo.getText();
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_fechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaNacActionPerformed
        fechaNac = LocalDate.parse(txt_fechaNac.getText());
    }//GEN-LAST:event_txt_fechaNacActionPerformed

    private void txt_biografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_biografiaActionPerformed
        biografia = txt_biografia.getText();
    }//GEN-LAST:event_txt_biografiaActionPerformed

    private void txt_sitioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sitioWebActionPerformed
        sitioWeb = txt_sitioWeb.getText();
    }//GEN-LAST:event_txt_sitioWebActionPerformed

    private void jButton_registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarUsuarioActionPerformed
    nickname = txt_nickname.getText();
    nombre = txt_nombre.getText();
    apellido = txt_apellido.getText();
    correo = txt_correo.getText();
    password = txt_password.getText();
    pass_conf = txt_password_confirmation.getText();
    
    try {
        // valida campos obligatorios
        if (nickname.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty() || password.isEmpty() || pass_conf.isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "ERROR: Faltan campos por completar.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        fechaNac = LocalDate.parse(txt_fechaNac.getText());
        
        if(fechaNac.getYear() < 1900){
            JOptionPane.showMessageDialog(this, 
                "ERROR: " + fechaNac.getYear() + " debe ser mayor a 1900.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(!jRadioButton_Artista.isSelected() && !jRadioButton_Cliente.isSelected()){
            JOptionPane.showMessageDialog(this, 
                "ERROR: Seleccione Tipo de Usuario.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        if(jRadioButton_Artista.isSelected()){
            biografia = txt_biografia.getText();
            sitioWeb = txt_sitioWeb.getText();
            tipo = Sistema.ARTISTA;
        } else if (jRadioButton_Cliente.isSelected()){
            biografia = null;
            sitioWeb = null;
            tipo = Sistema.CLIENTE;
        }

        // verifica la existencia del nickname
        if(sys.existeUsuario(nickname)){
            JOptionPane.showMessageDialog(this, 
                "Error: El usuario con el nickname " + nickname + " ya está registrado", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //si las pass conciden
        
        if(!password.equals(pass_conf)){
            JOptionPane.showMessageDialog(this,
                "Error: Las contraseñas no coinciden. Password: "+ password +" Confirmacion: "+ pass_conf,
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // verifica la existencia del correo electrónico
        if(sys.existeMail(correo)) {
            JOptionPane.showMessageDialog(this, 
                "Error: El correo " + correo + " ya está registrado", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // registra el usuario
        sys.altaPerfil(nickname, nombre, apellido, password, correo, fechaNac, imagenPerfil, biografia, sitioWeb, tipo);
        JOptionPane.showMessageDialog(this, 
            "Usuario registrado con éxito", 
            "Éxito", 
            JOptionPane.INFORMATION_MESSAGE);

    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, 
            "ERROR: fecha inválida. Use el formato YYYY-MM-DD.", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, 
            e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (UsuarioRepetidoException e) {
        JOptionPane.showMessageDialog(this, 
            "Error al registrar el usuario: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    
    // limpia campos
    txt_nickname.setText("");
    txt_nombre.setText("");
    txt_apellido.setText("");
    txt_correo.setText("");
    txt_fechaNac.setText("");
    txt_biografia.setText("");
    txt_sitioWeb.setText("");
    txt_password.setText("");
    txt_password_confirmation.setText("");
    }//GEN-LAST:event_jButton_registrarUsuarioActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        password = txt_password.getText();
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_password_confirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password_confirmationActionPerformed
        pass_conf = txt_password_confirmation.getText();
    }//GEN-LAST:event_txt_password_confirmationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_imagen;
    private javax.swing.JButton jButton_registrarUsuario;
    private javax.swing.JLabel jLabel_apellido;
    private javax.swing.JLabel jLabel_biografia;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_fechaNac;
    private javax.swing.JLabel jLabel_imagen;
    private javax.swing.JLabel jLabel_nickname;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_password_confirmation;
    private javax.swing.JLabel jLabel_sitioWeb;
    private javax.swing.JLabel jLabel_tipoUsuario;
    private javax.swing.JRadioButton jRadioButton_Artista;
    private javax.swing.JRadioButton jRadioButton_Cliente;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_biografia;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_fechaNac;
    private javax.swing.JTextField txt_nickname;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_password_confirmation;
    private javax.swing.JTextField txt_sitioWeb;
    // End of variables declaration//GEN-END:variables
}
