/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacionGUI;

import controladores.*;
import datatypes.*;
import excepciones.ListaRepetidaException;
import excepciones.UsuarioNoExisteException;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import persistencia.ControladorPersistencia;

/**
 *
 * @author dokgo
 */
public class CrearListaReproduccion extends javax.swing.JInternalFrame {
    ControladorPersistencia cpu;
    
    iSistema sys = new Fabrica().getSistema(cpu);
    public String imagen;

    /**
     * Creates new form CrearListaReproduccion
     */
    public CrearListaReproduccion() {
        initComponents();
        //sys = new Fabrica().getSistema();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        cbmTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblExtra = new javax.swing.JLabel();
        txtExtra = new javax.swing.JComboBox<>();
        btnImagen = new javax.swing.JButton();
        jLabel_imagen = new javax.swing.JLabel();
        jLabel_ERROR_nombre = new javax.swing.JLabel();
        jLabel_ERROR_Lista_PorDefecto = new javax.swing.JLabel();
        jLabel_EXITOSA = new javax.swing.JLabel();

        setTitle("Crear ListaReproduccion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 17, -1, -1));

        jLabel2.setText("Imagen:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 59, -1, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 14, 130, -1));

        cbmTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Por Defecto","Particular"}));
        cbmTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmTipoActionPerformed(evt);
            }
        });
        getContentPane().add(cbmTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 103, 130, -1));

        jLabel3.setText("Tipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 106, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 202, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 202, -1, -1));
        getContentPane().add(lblExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 145, -1, -1));

        txtExtra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        txtExtra.setVisible(false);
        txtExtra.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                txtExtraPopupMenuWillBecomeVisible(evt);
            }
        });
        getContentPane().add(txtExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 145, 130, -1));

        btnImagen.setText("Elegir Archivo");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });
        getContentPane().add(btnImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 56, -1, -1));
        getContentPane().add(jLabel_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 17, 262, 110));

        jLabel_ERROR_nombre.setText("Ingrese un nombre.");
        getContentPane().add(jLabel_ERROR_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 17, -1, -1));

        jLabel_ERROR_Lista_PorDefecto.setText("ERROR : ya existe una lista con ese nombre.");
        getContentPane().add(jLabel_ERROR_Lista_PorDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 232, -1, -1));

        jLabel_EXITOSA.setText("Operacion Exitosa!!");
        getContentPane().add(jLabel_EXITOSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 178, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
         jLabel_ERROR_Lista_PorDefecto.setVisible(false);
         jLabel_EXITOSA.setVisible(false);
        String nom = txtNom.getText();
        if(nom.isEmpty()){
            jLabel_ERROR_nombre.setVisible(true);
        }else{
        if(cbmTipo.getSelectedIndex()==0){
            String extra = txtExtra.getSelectedItem().toString();
            if(sys.Encontrar_Lista_Por_Defecto(nom)){
                jLabel_ERROR_Lista_PorDefecto.setVisible(true);
            }else{
            //poner el if si no hay genero o tipo
            jLabel_ERROR_Lista_PorDefecto.setVisible(false);
            DataLista dl = new DataLista(nom,imagen,extra);
            jLabel_EXITOSA.setVisible(true);
            try {
                sys.altaListaDef(dl);
            } catch (ListaRepetidaException ex) {
                Logger.getLogger(CrearListaReproduccion.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }else{
             String extra = txtExtra.getSelectedItem().toString();
             if(sys.Encontrar_Lista_Particular(extra,nom)){
                jLabel_ERROR_Lista_PorDefecto.setVisible(true);
            }else{
             DataLista dl = new DataLista(nom,imagen,extra);
             jLabel_EXITOSA.setVisible(true);
            try {
                sys.altaListaPart(dl);
            } catch (ListaRepetidaException ex) {
                Logger.getLogger(CrearListaReproduccion.class.getName()).log(Level.SEVERE, null, ex);
            }
             }
        }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cbmTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmTipoActionPerformed
        jLabel_ERROR_Lista_PorDefecto.setVisible(false);
        jLabel_EXITOSA.setVisible(false);
        if(cbmTipo.getSelectedIndex()==0){
            lblExtra.setText("Genero:");
            txtExtra.setVisible(true);
            txtExtra.removeAllItems();
            for(String s:sys.listarGeneros()){
                txtExtra.addItem(s);
            }
        }else{
            if(cbmTipo.getSelectedIndex()==1){
                lblExtra.setText("Cliente:");
                txtExtra.setVisible(true);
                txtExtra.removeAllItems();
                try {
                    for(DataUsuario dt:sys.getClientes()){
                        txtExtra.addItem(dt.getNick());
                    }
                } catch (UsuarioNoExisteException ex) {
                    Logger.getLogger(CrearListaReproduccion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                txtExtra.setVisible(false);
                txtExtra.removeAllItems();
                lblExtra.setText(" ");
            }
        }
    }//GEN-LAST:event_cbmTipoActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        jLabel_ERROR_Lista_PorDefecto.setVisible(false);
        jLabel_EXITOSA.setVisible(false);
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG & PNG","jpg","png");
        jFileChooser.setFileFilter(filtrado);
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if(respuesta == JFileChooser.APPROVE_OPTION){
        
            imagen = jFileChooser.getSelectedFile().getPath();
             
            Image mImagen = new ImageIcon(imagen).getImage();
            
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(jLabel_imagen.getWidth(),jLabel_imagen.getHeight(), Image.SCALE_SMOOTH));
           
            jLabel_imagen.setIcon(mIcono);
            
            jLabel_imagen.setVisible(true);
            
        }
    }//GEN-LAST:event_btnImagenActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        lblExtra.setText("Genero:");
            txtExtra.setVisible(true);
            txtExtra.removeAllItems();
             for(String s:sys.listarGeneros()){
                txtExtra.addItem(s);
            }
        jLabel_ERROR_nombre.setVisible(false);
        jLabel_ERROR_Lista_PorDefecto.setVisible(false);
        jLabel_EXITOSA.setVisible(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtExtraPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txtExtraPopupMenuWillBecomeVisible
        jLabel_ERROR_Lista_PorDefecto.setVisible(false);
        jLabel_EXITOSA.setVisible(false);
    }//GEN-LAST:event_txtExtraPopupMenuWillBecomeVisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JComboBox<String> cbmTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_ERROR_Lista_PorDefecto;
    private javax.swing.JLabel jLabel_ERROR_nombre;
    private javax.swing.JLabel jLabel_EXITOSA;
    private javax.swing.JLabel jLabel_imagen;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JComboBox<String> txtExtra;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
