/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacionGUI;

import controladores.Fabrica;
import controladores.iSistema;
import java.util.ArrayList;

/**
 *
 * @author dokgo
 */
public class DejarDeSeguirUsuario extends javax.swing.JInternalFrame {
    iSistema sys = new Fabrica().getSistema();
    /**
     * Creates new form DejarDeSeguirUsuario
     */
    public DejarDeSeguirUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ACEPTAR_DEJAR_DE_SEGUIR = new javax.swing.JButton();
        CANCELAR_DEJAR_DE_SEGUIR = new javax.swing.JButton();
        SELECCIONAR_CLIENTE = new javax.swing.JComboBox<>();
        SELECCIONAR_USUARIO = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Dejar de seguir a Usuario");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE NICKNAME DEL CLIENTE.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("INGRESE NICKNAME DEL USUARIO QUE DEJARA DE SEGUIR.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        ACEPTAR_DEJAR_DE_SEGUIR.setText("Aceptar");
        ACEPTAR_DEJAR_DE_SEGUIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ACEPTAR_DEJAR_DE_SEGUIRMousePressed(evt);
            }
        });
        ACEPTAR_DEJAR_DE_SEGUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTAR_DEJAR_DE_SEGUIRActionPerformed(evt);
            }
        });
        getContentPane().add(ACEPTAR_DEJAR_DE_SEGUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        CANCELAR_DEJAR_DE_SEGUIR.setText("Cancelar");
        CANCELAR_DEJAR_DE_SEGUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELAR_DEJAR_DE_SEGUIRActionPerformed(evt);
            }
        });
        getContentPane().add(CANCELAR_DEJAR_DE_SEGUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 120, -1, -1));

        SELECCIONAR_CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECCIONAR_CLIENTEActionPerformed(evt);
            }
        });
        getContentPane().add(SELECCIONAR_CLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, 175, -1));

        SELECCIONAR_USUARIO.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                SELECCIONAR_USUARIOPopupMenuWillBecomeVisible(evt);
            }
        });
        SELECCIONAR_USUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SELECCIONAR_USUARIOMousePressed(evt);
            }
        });
        getContentPane().add(SELECCIONAR_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 175, -1));

        jLabel3.setText("Seleccione un Cliente.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel4.setText("Seleccione un Usuario.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 87, -1, -1));

        jLabel5.setText("Operacion Exitosa!!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, -1, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ACEPTAR_DEJAR_DE_SEGUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTAR_DEJAR_DE_SEGUIRActionPerformed
       
    }//GEN-LAST:event_ACEPTAR_DEJAR_DE_SEGUIRActionPerformed

    private void CANCELAR_DEJAR_DE_SEGUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELAR_DEJAR_DE_SEGUIRActionPerformed
      this.setVisible(false);
        
    }//GEN-LAST:event_CANCELAR_DEJAR_DE_SEGUIRActionPerformed

    private void SELECCIONAR_CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECCIONAR_CLIENTEActionPerformed
        SELECCIONAR_USUARIO.removeAllItems();
    }//GEN-LAST:event_SELECCIONAR_CLIENTEActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        ArrayList<String> Nicknames_Clientes = new ArrayList<String>();
        Nicknames_Clientes = sys.Nicknames_De_Clientes();
        for(int i = 0; i < Nicknames_Clientes.size(); i++){
        
        SELECCIONAR_CLIENTE.addItem(Nicknames_Clientes.get(i));
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void SELECCIONAR_USUARIOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SELECCIONAR_USUARIOMousePressed
      
    }//GEN-LAST:event_SELECCIONAR_USUARIOMousePressed

    private void ACEPTAR_DEJAR_DE_SEGUIRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACEPTAR_DEJAR_DE_SEGUIRMousePressed
        
        if(SELECCIONAR_CLIENTE.getSelectedItem() == null){
           jLabel3.setVisible(true);
           if(SELECCIONAR_USUARIO.getSelectedItem() ==  null){
                jLabel4.setVisible(true);
           }
           }else{
           if(SELECCIONAR_USUARIO.getSelectedItem() ==  null){
               jLabel4.setVisible(true);
           }else{
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                String cliente = SELECCIONAR_CLIENTE.getSelectedItem().toString();
                String usuario = SELECCIONAR_USUARIO.getSelectedItem().toString();
                sys.Dejar_De_Seguir_Usuario(cliente, usuario);
                SELECCIONAR_USUARIO.removeAllItems();
                jLabel5.setVisible(true);
           }
       }
    }//GEN-LAST:event_ACEPTAR_DEJAR_DE_SEGUIRMousePressed

    private void SELECCIONAR_USUARIOPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_SELECCIONAR_USUARIOPopupMenuWillBecomeVisible
        SELECCIONAR_USUARIO.removeAllItems(); 
        if(SELECCIONAR_USUARIO.getItemCount() == 0){
        String cliente_seleccionado = SELECCIONAR_CLIENTE.getSelectedItem().toString();
         ArrayList<String> meto = sys.Listar_Usuarios_A_DEJAR_DE_Seguir(cliente_seleccionado);
             for (int i = 0; i < meto.size(); i++) {
            SELECCIONAR_USUARIO.addItem(meto.get(i));
            }
    } 
    }//GEN-LAST:event_SELECCIONAR_USUARIOPopupMenuWillBecomeVisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR_DEJAR_DE_SEGUIR;
    private javax.swing.JButton CANCELAR_DEJAR_DE_SEGUIR;
    private javax.swing.JComboBox<String> SELECCIONAR_CLIENTE;
    private javax.swing.JComboBox<String> SELECCIONAR_USUARIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
