/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacionGUI;
import logica.Usuario;
import controladores.iSistema;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import logica.Cliente;
import controladores.Fabrica;
import java.util.ArrayList;

/**
 *
 * @author dokgo
 */
public class SeguirUsuario extends javax.swing.JInternalFrame {
    iSistema sys = new Fabrica().getSistema();
    /**
     * Creates new form SeguirUsuario
     */
    public SeguirUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_ClienteQueSigue = new javax.swing.JComboBox<>();
        jComboBox_UsuarioASeguir = new javax.swing.JComboBox<>();
        ACEPTAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Seguir a Usuario");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("SELECCIONE UN CLIENTE.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setText("SELECCIONE UN USUARIO A SEGUIR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, -1, -1));

        jComboBox_ClienteQueSigue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ClienteQueSigueActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_ClienteQueSigue, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 169, -1));

        jComboBox_UsuarioASeguir.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox_UsuarioASeguirPopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox_UsuarioASeguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox_UsuarioASeguirMousePressed(evt);
            }
        });
        getContentPane().add(jComboBox_UsuarioASeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 96, 169, -1));

        ACEPTAR.setText("Aceptar");
        ACEPTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ACEPTARMousePressed(evt);
            }
        });
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });
        getContentPane().add(ACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, -1, -1));

        CANCELAR.setText("Cancelar");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });
        getContentPane().add(CANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 138, -1, -1));

        jLabel3.setText("Seleccione un cliente.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 33, -1, -1));

        jLabel4.setText("Seleccione un Usuario.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 99, -1, -1));

        jLabel6.setText("Operacion Exitosa.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 168, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ClienteQueSigueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ClienteQueSigueActionPerformed
        jComboBox_UsuarioASeguir.removeAllItems();
      
    }//GEN-LAST:event_jComboBox_ClienteQueSigueActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel6.setVisible(false);
        ArrayList<String> Nicknames_Clientes = new ArrayList<String>();
        Nicknames_Clientes = sys.Nicknames_De_Clientes();
        for(int i = 0; i < Nicknames_Clientes.size(); i++){
        
        jComboBox_ClienteQueSigue.addItem(Nicknames_Clientes.get(i));
        }
        
    }//GEN-LAST:event_formInternalFrameActivated

    
    
    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        
        if(jComboBox_ClienteQueSigue.getSelectedItem() == null){
           jLabel3.setVisible(true);
           if(jComboBox_UsuarioASeguir.getSelectedItem() ==  null){
                jLabel4.setVisible(true);
           }
           }else{
           if(jComboBox_UsuarioASeguir.getSelectedItem() ==  null){
               jLabel4.setVisible(true);
           }else{
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                //String cliente = jComboBox_ClienteQueSigue.getSelectedItem().toString();
                //String usuario = jComboBox_UsuarioASeguir.getSelectedItem().toString();
                
                sys.Seguir_Usuario(jComboBox_ClienteQueSigue.getSelectedItem().toString(), jComboBox_UsuarioASeguir.getSelectedItem().toString());
                jComboBox_UsuarioASeguir.removeAllItems();
                jLabel6.setVisible(true);
           }
       }
      
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CANCELARActionPerformed
    
    private void jComboBox_UsuarioASeguirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_UsuarioASeguirMousePressed
     // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_UsuarioASeguirMousePressed

    private void ACEPTARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACEPTARMousePressed
      
       
      
    }//GEN-LAST:event_ACEPTARMousePressed

    private void jComboBox_UsuarioASeguirPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox_UsuarioASeguirPopupMenuWillBecomeVisible
         jLabel6.setVisible(false);
        if(jComboBox_UsuarioASeguir.getItemCount() == 0){
            String cliente_seleccionado = jComboBox_ClienteQueSigue.getSelectedItem().toString();
           
        ArrayList<String> meto = sys.Listar_Usuarios_A_Seguir(cliente_seleccionado);
             for (int i = 0; i < meto.size(); i++) {
                 if(cliente_seleccionado == meto.get(i)){
                     
                 }else{
            jComboBox_UsuarioASeguir.addItem(meto.get(i));
            }
             } 
   
        }
    }//GEN-LAST:event_jComboBox_UsuarioASeguirPopupMenuWillBecomeVisible
    





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JComboBox<String> jComboBox_ClienteQueSigue;
    private javax.swing.JComboBox<String> jComboBox_UsuarioASeguir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
